FROM python:3.11-slim

WORKDIR /app/

COPY . /app/

RUN pip install --upgrade pip \
&& pip install -r requirements.txt \
&& python manage.py makemigrations \
&& python manage.py migrate

CMD python manage.py runserver 0.0.0.0:8000