# Generated by Django 5.0.6 on 2024-07-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_city_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
    ]
