# Generated by Django 5.0.6 on 2024-07-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trip_max_passengers_remove_trip_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='car',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
            preserve_default=False,
        ),
    ]
