# Generated by Django 5.0.6 on 2024-07-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_car_color_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, null=True, related_name='trip_passengers', to='main.userprofile'),
        ),
    ]
