# Generated by Django 5.0.6 on 2024-07-07 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_trip_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.userprofile'),
        ),
    ]
