# Generated by Django 5.0.6 on 2024-07-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='trip_car', to='main.car'),
            preserve_default=False,
        ),
    ]
