# Generated by Django 5.0.6 on 2024-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_trip_pending_passengers_alter_trip_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
