# Generated by Django 4.2.14 on 2024-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/img/default.jpg', upload_to='avatars/'),
        ),
    ]
