# Generated by Django 5.0.6 on 2024-08-28 23:37

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(default=main.utils.generate_secret_token, max_length=255),
        ),
    ]
